apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-deployment
  labels:
    app: online
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online
  template:
    metadata:
      labels:
        app: online
    spec:
      containers:
      - name: online
        image: venkatv11/mani123
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: online-service
spec:
  selector:
    app: online
  ports:
    - protocol: TCP
      port: 8080 # Exposed port on the Service
      targetPort: 8081 # Port inside the container (Tomcat)
  type: LoadBalancer  # External acces
